### ISSUE TITLE
debughook-ptr-leak.cpp results 0 

### ISSUE THREAD

**Issue by amanszpapaya** [gdabah/win32k-bugs#1]
Hi,

I have built debughook-ptr-leak.cpp on a Windows 10x64 machine like you suggested. However when I run the exe created as an administrator it gives me the leaked kernel address 0 like the following:

<img width="1060" alt="Screen Shot 2019-12-19 at 09 38 35" src="https://user-images.githubusercontent.com/40626848/71169755-c0846000-226a-11ea-883e-75b450fb9b9a.png">

Can you help?

**Comment by gdabah** [comment]
You will have to make sure the constants used throughout the code (mostly the function number to hook) are all correct for your version. That is, given you're not using an up to date version that already fixed this bug.

**Comment by amanszpapaya** [comment]
It seems that only changes that occur in the debughook-ptr-leak.cpp file is file name and CVE number constant value and remaining part code is exactly the same in all commits.

**Comment by gdabah** [comment]
I meant version of windows you use. Good luck.
